### ISSUE TITLE
Contact reference 'not a valid integer'

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/civicrm_entity#117]
Hi,

I've found a problem that I'd like to report but also I'm prepared to put in some effort to fix - I just need a pointer or two.

I have some code that loads a CiviEvent entity and then saves it (to force a Drupal computed field to update) ...

    $entities = entity_load('civicrm_event', $params)
    foreach ($entities as $entity) {
      entity_save('civicrm_event', $entity)
    }

The save operation raises an exception 'custom_62 is not a valid integer'. custom_62 is a Contact Reference field.

I see that attribute 'custom_62' is set to a contact name, and 'custom_62_id' is the contact id. The following code prevents the exception and 'does no harm' (the contact reference field remains unchanged as I desired) ...

    $entities = entity_load('civicrm_event', $params)
    foreach ($entities as $entity) {
      $entity->custom_62 = $entity->custom_62_id;
      entity_save('civicrm_event', $entity)
    }

It appears that the entity_load has set up the custom_62_id but the entity_save ignores it.

**Comment by kenwest** [comment]
It seems to me that the asymmetry between load() and save() is a feature of the CiviCRM API.

Perhaps a fix would be to add the following lines to CivicrmEntityController::save() just prior to the call to the API ...

    /*
     * If there is a 'custom_N_id' parameter and 'custom_N' is not a number, then
     * overwrite 'custom_N' (assumes it is a label and CiviCRM expects an Id).
     * Unset 'custom_N_id' as the API will ignore it.
     */
    foreach ($params as $key => $value) {
      if (substr($key, 0, 7) === 'custom_' && substr($key, -3) === '_id') {
        $customkey = substr($key, 0, strlen($key) - 3);
        if (!is_numeric($params[$customkey]) && is_numeric($params[$key])) {
          $params[$customkey] = $params[$key];
        }
        unset($params[$key]);
      }
    }

**Comment by jackrabbithanna** [comment]
@kenwest I've just noticed this in the issue queue. Usually monitor the issue queue on the Drupal.org project page. Has this code worked out for you?

**Comment by kenwest** [comment]
@jackrabbithanna I've only tried the hack in my first comment.

**Comment by jackrabbithanna** [comment]
Fix in for this (finally) thanks @kenwest ... fix in 7.x-2.x-dev on D.O project page. Will be included in upcoming 2.2 release
