### ISSUE TITLE
Created Drupal username does not get trimmed well

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/civicrm_entity#135]
hi there,
I found out the constructed username for creating a drupal account doesn't get trimmed very well.
When a user enters a first,middle or lastname with an extra space in front or at the end the it will be replaces by a _ in the final username.
This PR solves it for us but maybe there are better alternatives: https://github.com/eileenmcnaughton/civicrm_entity/pull/134

**Comment by jackrabbithanna** [comment]
PR was merged, closing issue
