### ISSUE TITLE
check contact exist in group before deleting it  to avoid multiple log in watchdog

### ISSUE THREAD

**Issue by sunilpawar** [eileenmcnaughton/civicrm_entity#179]
we have Drupal rule module configured to remove contact from group if certain criteria not meet.

Most of contact does not present in Group specified in Rules, This add N number of log watchdog, 

catch block only be called when there is error in removing contact from group.

**Comment by jackrabbithanna** [comment]
Confirmed that if a contact is NOT in the group specified by the action settings, and the action runs a 'delete' action for the GroupContact entity, this causes the APIv3 to throw an exception, which is caught by a catch block and logs a message to the Drupal log. Thanks for the PR Sunil!

**Comment by jackrabbithanna** [comment]
PR merged and pushed to Drupal.org, -dev branch, to be included in next release
