### ISSUE TITLE
Date of Birth Field -> renders blank when creating a View

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#189]
**Steps to reproduce:**
1. (top part): View of CiviCRM Contact -> fields: Name, Birth Date, Created Date, Contact id.
2. (middle part): Birth Date is blank -> Created Date is ok.
3. (bottom part): in CiviCRM Contact with id = 2 -> definitively has a Date of Birth -> June 5, 1970

Same issue when using Contact Rendered Entity.

![image](https://user-images.githubusercontent.com/5340555/67052339-14ec5180-f0fb-11e9-9389-8a50cea53ac4.png)

**Comment by mglaman** [comment]
I bet this is due to the ways times are stored. Drupal had some improvements in 8.6 or 8.7.

For instance, JSON API needed a Unix timestamp for filters and not time strings. This is now fixed in core.

**Comment by KarinG** [comment]
Ah -> I’m on D8.7 here

**Comment by KarinG** [comment]
Confirmed fixed by https://github.com/eileenmcnaughton/civicrm_entity/pull/190
