### ISSUE TITLE
Custom Fields on Contact can be pulled into View; Custom Fields on Membership can not.

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#193]
**1. This is working: Custom Fields on Contact**

Structure -> CiviCRM Entity -> Settings
Enable (check) Custom Field

Structure -> Views -> Add View:
CiviCRM Contacts
Configure:

![image](https://user-images.githubusercontent.com/5340555/67732572-6df09b00-f9c1-11e9-9caa-35a67f8b6ee7.png)

Cookie preference is a Custom Field on: the Contact Entity - it lives in:

![image](https://user-images.githubusercontent.com/5340555/67732784-1a328180-f9c2-11e9-91c5-2a88597f43d3.png)

**2. This is not working: Custom Fields on Membership**

Using the same logic and starting with a View of CiviCRM Memberships - I can't add a Custom Field on Membership. The field does not appear in the View GUI to add a field.

![image](https://user-images.githubusercontent.com/5340555/67732901-72698380-f9c2-11e9-8432-cc1f6388de06.png)

![image](https://user-images.githubusercontent.com/5340555/67732690-c9bb2400-f9c1-11e9-9a55-6804b0202e73.png)

**Comment by jackrabbithanna** [comment]
Does this issue still exist for you? I'm not able to replicate this. I can add custom fields to a View for Membership entity type. 

You do have to clear Drupal caches after adding a custom field in Civi.

Let me know if you still have trouble with this, but custom fields are fixing to change how they are handled. 

Soon we'll have a PR where you see the custom field group table listed in the "Category" select list in the header, like it was in Drupal 7 version anyway.

Closing for now.
