### ISSUE TITLE
CiviCRM Entity breaks in Drupal 8.8

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/civicrm_entity#195]
Installing the module fails with errors:

> PHP Fatal error:  Uncaught Error: Call to a member function getFieldStorageDefinitions() on null in /var/www/html/distro8.skvare.com/web/core/modules/views/src/EntityViewsData.php:132
> Stack trace:
> #0 /var/www/html/distro8.skvare.com/web/core/modules/views/src/EntityViewsData.php(415): Drupal\views\EntityViewsData->getFieldStorageDefinitions()
> #1 /var/www/html/distro8.skvare.com/web/modules/custom/civicrm_entity/src/CivicrmEntityViewsData.php(117): Drupal\views\EntityViewsData->mapFieldDefinition('civicrm_action_...', 'id', Object(Drupal\Core\Field\BaseFieldDefinition), Object(Drupal\Core\Entity\Sql\DefaultTableMapping), Array)
> #2 /var/www/html/distro8.skvare.com/web/core/modules/views/views.views.inc(178): Drupal\civicrm_entity\CivicrmEntityViewsData->getViewsData()
> #3 [internal function]: views_views_data()
> #4 /var/www/html/distro8.skvare.com/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('views_views_dat...', Array)
> #5 /var/www/html/distro8.skvare.com/web/core/modules/views/src/ViewsData.php( in /var/www/html/distro8.skvare.com/web/core/modules/views/src/EntityViewsData.php on line 132
>  [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site

**Comment by jackrabbithanna** [comment]
This may be just an issue with Drupal 8.8-beta1 .. seeing this error with Civi tables in same database

**Comment by jonhalle** [comment]
I also have this issue. I updated D8 site using composer which took it to D8.8 and got the same error.

**Comment by stesi561** [comment]
Per comment on chat (https://chat.civicrm.org/civicrm/pl/8ms1a8ggtpfmuya74roq4hbeza) I tried installing devel_entity_updates to see if this would help. Still getting the above error on install. And cache clearing.

**Comment by stesi561** [comment]
I've had a bit of a poke at this. I'm wondering if this problem is changes to EntityViewsData in views - notably it looks like the constructor has changed. And an extra arg has been added - but is not called. 

There is additionally a removal of the 
Drupal\Core\Entity\EntityManagerInterface
which seems to be replaced with the 
Drupal\Core\Entity\EntityTypeManagerInterface

  In commit a98b58765d1 (Drupal core). This appears to be present in 8.8.x branch but not 8.7.x
The commit references
https://www.drupal.org/project/drupal/issues/3035953

Which references
https://www.drupal.org/project/drupal/issues/2886622

**Comment by stesi561** [comment]
This fixes the error - I'm not clear if this might lead to breaking something else as this is my first venture into civi entity + d8  https://github.com/eileenmcnaughton/civicrm_entity/pull/199

**Comment by dsnopek** [comment]
@mglaman Can you take a peek at this?

**Comment by mglaman** [comment]
@dsnopek the fix looks good; I think it was a "support 8.6" thing.

**Comment by jackrabbithanna** [comment]
Merged the PR and it seems to be working good for us.
