### ISSUE TITLE
Base table not found for civicrm_contribution_page

### ISSUE THREAD

**Issue by pradpnayak** [eileenmcnaughton/civicrm_entity#201]
On latest version of 8.x-3.x branch i get  following error when try to add a view for contribution page

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'civicrmdb.civicrm_contribution_page' doesn't exist: SELECT civicrm_contribution_page.id AS id FROM {civicrm_contribution_page} civicrm_contribution_page LIMIT 11 OFFSET 0; Array ( )

views for Contact, Contribution, Event works fine but not incase of Contribution page, Payment processor, campaign etc.

**Comment by jackrabbithanna** [comment]
@pradpnayak Does this issue still happen for you? I'm not able to replicate this in current version and Drupal 8.8

**Comment by jackrabbithanna** [comment]
FYI .. testing on a installation where the Civi tables are in a separate DB, and similar database integration in the settings.php that we had to use for Drupal 7.

I wonder if that is making a difference for me. Is this issue unique to standard D8 install with civi tables in Drupal db and no prefix information in settings.php

**Comment by jackrabbithanna** [comment]
Possibly related to: https://github.com/eileenmcnaughton/civicrm_entity/issues/198

**Comment by jackrabbithanna** [comment]
I tested this in a instance where Civi tables are in the Drupal DB, and I still cannot replicate this.

**Comment by pradpnayak** [comment]
Hi @jackrabbithanna 

if the civi database is separate and cms integration are not in drupal settings.php, then yes i could still replicate the problem

**Comment by jackrabbithanna** [comment]
With this Core PR: https://github.com/civicrm/civicrm-core/pull/17232 Drupal 8 version outputs the necessary $database variable prefix information for the settings.php and we're back to what was general requirements for the Drupal 7 version. 

Closing issue.
