### ISSUE TITLE
D8 Views issue with custom field filter

### ISSUE THREAD

**Issue by gibsonoliver** [eileenmcnaughton/civicrm_entity#219]
Hi

On 8.x-3.x-dev latest and Civi 5.24.4.
The settings.php file has the CMS integration settings added 
$databases['default']['default']['prefix']= array etc.

I tried to add a View looking at organisations and filtering on a custom Yes/No field only. 
No other settings added. I can add the filter but it throws an error 

Error is
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'civicrm_contact.custom_45' in 'where clause': SELECT civicrm_contact.id AS id FROM {civicrm_contact} civicrm_contact WHERE ((civicrm_contact.contact_type = :civicrm_contact_contact_type)) AND (civicrm_contact.custom_45 = :db_condition_placeholder_0) LIMIT 51 OFFSET 0; Array ( [:civicrm_contact_contact_type] => Organization [:db_condition_placeholder_0] => 1 )

Olly

**Comment by jackrabbithanna** [comment]
I think that you need to pull the code from the github repo, the latest stuff has not been pushed to drupal.org repo where composer require drupa/civicrm_entity pulls from.

I planned on doing that soon, to update drupal.org dev branch

**Comment by gibsonoliver** [comment]
Thanks Mark
I think with our D8 setup we may be stuck with what composer can pull from.
Can you let me know when you update the drupal.org branch and we'll run some tests.

Olly

**Comment by jackrabbithanna** [comment]
This issue should be resolved
