### ISSUE TITLE
Cannot redeclare class CivicrmEntityMetadataController

### ISSUE THREAD

**Issue by pat-cb** [eileenmcnaughton/civicrm_entity#22]
Was getting this issue occasionally. Pretty sure it's safe to wrap the declaration of CivicrmEntityMetadataController in a check for whether the class exists before declaring it. Will submit a PR shortly :-)

**Comment by xurizaemon** [comment]
Actually, I'm not sure about @pat-cb's issue here, and I opened #43 which may or may not be the same underlying problem.
