### ISSUE TITLE
How to use Custom Map Icon in CiviCRM Entity Address Leaflet Map

### ISSUE THREAD

**Issue by olivierh65** [eileenmcnaughton/civicrm_entity#233]
Hi,
I want to show events on a map, each with a custom icon based on event type.
I think that it's possible to define URL with Replacement Patterns... but how can I know which patterns are available?

Regards,
Olivier.

**Comment by olivierh65** [comment]
I've created pull request #236 that display available replacement pattern.

**Comment by jackrabbithanna** [comment]
Referenced PR was merged -- being included in beta2 release tomorrow
