### ISSUE TITLE
Better Handling of Custom fields with multi options when integrating with other modules such as GraphQL

### ISSUE THREAD

**Issue by seamuslee001** [eileenmcnaughton/civicrm_entity#235]
Recently for a project I have been needing to use the GraphQL endpoint module (working on a Dart/Flutter App and the go to way to access external resources appears to be via GraphQL)

One thing that I did run into is that for a multivalue custom field (e.g. Checkboxes etc) The GraphQL endpoint would only return the one value.  This is because even tho we use a List Style this code here https://git.drupalcode.org/project/graphql/-/blob/8.x-3.x/modules/graphql_core/src/Plugin/Deriver/Fields/EntityFieldDeriver.php#L53 changes it from a type of `[String]` to be just `String` because it doesn't detect the field handles Multiple Values. This seems to be because the cardinality for custom field objects created via CiviCRM entity is 1 no matter how many actual values it can store which then leads the isMultiple() to return FALSE. I tried locally to change the cardinality to > 1 but that broke in other ways as it started assuming there was dedicated tables etc. But just putting it here for ideas. For our specific usage I managed to work around it but it would be nice to have better handling. 

@jackrabbithanna

**Comment by jackrabbithanna** [comment]
This is accurate. The entity only loads one custom field value. This is because on entity load, there is a 'get' API call for that entity type, with a 'return' property for all the custom fields, and that way only returns the latest custom field value. We'd have to get into appending the additional field values, by doing a 'CustomValue' APi call to fetch them all, and add them to entity object appropriately.

**Comment by jackrabbithanna** [comment]
To load the entity data

Entity load: https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/CiviEntityStorage.php#L156
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/CiviEntityStorage.php#L179
To here: https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/CiviEntityStorage.php#L197
Maybe code here to get additional custom values:
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/CiviEntityStorage.php#L337

I think here to set the cardinality based on whether the custom field group is multiple:
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Entity/FieldDefinitionProvider.php#L14

**Comment by jackrabbithanna** [comment]
We may have a fix coming for better handling of single value custom field groups, but custom fields that have multiple options like, Alphanumeric type with checkboxes widget ... Coming soon. We were working on it for Drupal version of edit forms, but it may apply to your case too.

When I first read this issue, I was thinking more about custom groups that allow multiple field value sets .. which is another area that needs improvement

**Comment by jackrabbithanna** [comment]
Just merged a PR that may help with your case: https://github.com/eileenmcnaughton/civicrm_entity/pull/253

Let us know if that helps.

**Comment by jackrabbithanna** [comment]
No feedback in several months, closing
