### ISSUE TITLE
Not honouring CiviCRM permissions

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#240]
If I configure a View to be unrestricted:
![image](https://user-images.githubusercontent.com/5340555/95664569-6361df80-0b06-11eb-9b1c-1b535fcc5bf0.png)

Anonymous can see the Contacts even though role Anonymous has no CiviCRM access/permissions to see any Contacts.

If I configure the View to be -> role -> authenticated only -> then indeed Anonymous can no longer see the Contacts. 

So the Views Setting -> Page: Access Restrictions is working - but it looks like CiviCRM entity is not taking into account either Drupal CMS permissions (or CiviCRM ACLs).

**Comment by jackrabbithanna** [comment]
Yep Views access control is a little looser, especially if you are not rendering a Drupal entity view mode. Table of Fields won't engage it. 

Putting this in the category of a feature request.

**Comment by KarinG** [comment]
Thanks Mark.

**Comment by KarinG** [comment]
Closing this as I think it's ✅ to let Views handle permissions; and future work for civicrm-entity view/edit/delete etc would be to remove the hardcoded permissions from code - and to handle it with a node access module.
