### ISSUE TITLE
Drupal 9 compatibility report

### ISSUE THREAD

**Issue by codebymikey** [eileenmcnaughton/civicrm_entity#243]
The module doesn't yet support Drupal 9.

<strong>Drupal 9 Compatibility audit tasks</strong>
<ol>
  <li>Run <a href="https://github.com/mglaman/drupal-check">Drupal Check</a> on the latest 8.x branch to find deprecated code</li>
  <li>Run <a href="https://github.com/palantirnet/drupal-rector">Drupal Rector</a> on the module to automate some D9 compatibility</li>
</ol>

<strong>Deprecated code status:</strong>
TODO

<strong>Drupal 9 Compatibility checklist</strong>
- [ ] An automatable test exists that can be run against the Drupal core 9.x branch to verify minimum compatibility
- [ ] No Drupal 9-deprecated code deprecated exists in the codebase per drupal-check
- [ ] The info.yml file meets Drupal 9 syntax requirements (Add <em>core_version_requirement: ^8 || ^9,</em> unless additional specificity is required (see https://www.drupal.org/node/3070687))
- [ ] “Drupal 9 porting info” exists on the project page

Might also be worth applying @ryanaslett's latest fix for [the dependency issue](https://www.drupal.org/project/civicrm_entity/issues/3031344#comment-13854433).

**Comment by stesi561** [comment]
I've had a first cut at fixing the issues flagged by Drupal Check -> https://github.com/eileenmcnaughton/civicrm_entity/pull/247

I couldn't get Drupal Rector to run correctly and there were only a few so have covered them off manually.

**Comment by jackrabbithanna** [comment]
Fixes have been included in -dev version and beta2 being released tomorrow
