### ISSUE TITLE
Per-table prefixes are deprecated as of Drupal 8.2, will be removed in Drupal 9.0. After that, only a single prefix for all tables will be supported.

### ISSUE THREAD

**Issue by luenemam** [eileenmcnaughton/civicrm_entity#259]
Are you aware of
Per-table prefixes are deprecated as of Drupal 8.2, will be removed in Drupal 9.0. After that, only a single prefix for all tables will be supported.
https://www.drupal.org/node/2768219

It's still not removed in Drupal 9.
But is there another way to user Drupal Views with CiviCRM installed in a separate Database?

**Comment by jackrabbithanna** [comment]
We've had success using CiviCRM Entity with Drupal 9, with CiviCRM tables in a separate database. 
You can grab the integration code that CiviCRM needs from /civicrm/admin/setting/uf?reset=1
Then place that code into setting.php or settings.local.php

Be aware, for Drupal 9, you must remove the backticks `

**Comment by jackrabbithanna** [comment]
Yep this is probably an issue. We'll need to figure that out. We'll hope in the meantime removing per table prefixes is delayed until Drupal 10

**Comment by jackrabbithanna** [comment]
Someone working on tests, may have arrived at what to do to get ready for this:
https://github.com/eileenmcnaughton/civicrm_entity/pull/306#issuecomment-842813329

Where we update the Views integration code sort of like this:
```
    $data[$views_base_table]['table']['base'] = [
      'field' => $base_field,
      'title' => $this->entityType->getLabel(),
      'cache_contexts' => $this->entityType->getListCacheContexts(),
+     'database' => drupal_valid_test_ua() ? 'civicrm_test' : 'civicrm',
    ];
```
Will be testing this out sometime soon.
Would need like this in the settings.local.php

```
$databases['civicrm']['default'] = array (
  'database' => 'cividatabasename',
  'username' => 'user name',
  'password' => 'password',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
```

**Comment by luenemam** [comment]
Drupal is preparing to [Remove per-table prefixing](https://www.drupal.org/project/drupal/issues/3124382) in Drupal 11. The issue is currently "Reviewed & tested by the community"

But [Notify in Status Report that per-table database prefixes are no longer supported, and will throw errors in Drupal 10.0](https://www.drupal.org/project/drupal/issues/3106531) has landed.

**Comment by jackrabbithanna** [comment]
We are aware of this. Have WIP PR that is still under discussion/testing to stay on top of this:
https://github.com/eileenmcnaughton/civicrm_entity/pull/355

**Comment by jackrabbithanna** [comment]
MR has been merged into 8.x-3.x branch and will be going out soon to version 3.2 on Drupal.org
