### ISSUE TITLE
Display Name is required?

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#287]
Came across this -> parking here for now:

`civicrm-contact/add
`
Display Name is a required field. Typically required to create CiviCRM contacts -> Contact Type + First Name + Last Name

![image](https://user-images.githubusercontent.com/5340555/114183223-af001500-9900-11eb-9cc7-e1dc96c74be3.png)

**Comment by jackrabbithanna** [comment]
Haha yep .. I could make issues for about 20 different little things related to forms that could use tweaks. 

The field metadata is pretty much automated. Based on 'getfields' API call for the entity type where action = 'create'

I don't see sort_name or display_name showing as required with an API call ..
Good catch, definitely a bug.

**Comment by jackrabbithanna** [comment]
Places that field metadata gets set to required .. nothing obvious sticking out to me yet:
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Entity/CivicrmEntity.php#L114
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Entity/CivicrmEntity.php#L118
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/Entity/FieldDefinitionProvider.php#L113

**Comment by KarinG** [comment]
I think it may be this -> 
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/SupportedEntities.php#L142

**Comment by jackrabbithanna** [comment]
Hmm yep. there it is. Display name at least, not sort name.
I wonder if we should just not set required fields in SupportedEntities .. and base everything off of 'getfields' API call metadata.

**Comment by KarinG** [comment]
Ah - I actually mean display_name - my screenshot is correct but my Title -> fingers defaulted to sort_name - will Edit that.
