### ISSUE TITLE
What are these strings?

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#288]
Found this during a round of testing on a clean install (prior to the bundle PR) - what do strings like these represent?

![image](https://user-images.githubusercontent.com/5340555/114238062-3cfbf000-9941-11eb-9fda-3cc914210c3c.png)

**Comment by jackrabbithanna** [comment]
When you manage the layout for all entities of an entity type, it looks like Drupal is providing some default values for different fields in the layout builder. I do not know yet how that is generated. 

When I configure an entity type to be able to configure layout per entity, the actual field values are displayed. 

It is a bit bizarre no doubt.
