### ISSUE TITLE
Error Activity/Event with bundles + layout builder restrictions module

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/civicrm_entity#295]
@mglaman I wonder if I can have your thoughts on this issue

Pinging @KarinG 

Doing some more testing with our module set, and another possible issue with those entity types which have had bundle support added. 

New error when Layout Builder Restrictions module is enabled for an entity type

Issue is replicable only for Event or Activity types, with the bundle patch previously discussed. 

Issue only manifests when an entity type is allowed to have layout configured per entity. Manage the layout for a specific entity, and try to add a block to a section.
Adding a block to the default layout for all entities of a type, on the "Manage Display" area,  does not manifest error. 

No errors with entity type layout or per entity layouts for entity types without bundles. 

When trying to add a "block" to a layout section, there is a ajax error, is is caused by the ajax request having a 500 error. 

Error: Call to a member function getThirdPartySetting() on null in Drupal\layout_builder_restrictions\Plugin\LayoutBuilderRestriction\EntityViewModeRestriction->inlineBlocksAllowedinContext() (line 274 of /var/www/html/demo8.skvare.com/web/modules/contrib/layout_builder_restrictions/src/Plugin/LayoutBuilderRestriction/EntityViewModeRestriction.php)

#0 /var/www/html/demo8.skvare.com/web/modules/contrib/layout_builder_restrictions/src/Controller/ChooseBlockController.php(27): Drupal\layout_builder_restrictions\Plugin\LayoutBuilderRestriction\EntityViewModeRestriction->inlineBlocksAllowedinContext(Object(Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage), '1', 'blb_region_col_...')
#1 [internal function]: Drupal\layout_builder_restrictions\Controller\ChooseBlockController->build(Object(Drupal\layout_builder\Plugin\SectionStorage\OverridesSectionStorage), '1', 'blb_region_col_...')
#2 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#3 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#5 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#6 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/www/html/demo8.skvare.com/vendor/symfony/http-kernel/HttpKernel.php(151): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/demo8.skvare.com/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/demo8.skvare.com/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/demo8.skvare.com/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/html/demo8.skvare.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/demo8.skvare.com/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/demo8.skvare.com/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))

**Comment by jackrabbithanna** [comment]
A case could be made that this is a bug in Layout Builder Restrictions module. 

That being said, it seems that if that module did checks that prevented the error, we still would not be able to utilize this module when CE entity types have bundles.

If we were to have config to Manage Fields / Manage Display etc.. for each bundle type, this would not be an issue. But that would be a major UI/UX headache to have to configure displays etc.. for each activity type. 

Is there some middle way .. a way that this bit of code ends up with $view_display not being null:
```
$context = $entity_type . "." . $bundle . "." . $view_mode;
$storage = \Drupal::entityTypeManager()->getStorage('entity_view_display');
$view_display = $storage->load($context);
```

Right now I'm testing with Event entity type, trying to add a block to a layout for a specific event, The event has Event Type = Meeting
the context variable has value:
civicrm_event.meeting.full

**Comment by mglaman** [comment]
I will take a look at this in the next few days. To me they are assuming that the entity display mode is saved. Which with layout builder is typical. So they do not do the fallback of " if not exist load the default end quote. So what we can do is in previous areas we have mocked or forced it to fall back to the default.

We're now going into countryland that extends layout builder which honestly means bugs anyways especially for layout builder and trip. But I'll take a look at it It shouldn't be that hard to work around

**Comment by jackrabbithanna** [comment]
This disappeared at some point via other updates, or Drupal core updates. Closing issue
