### ISSUE TITLE
Access control discussion

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/civicrm_entity#296]
I'm making this issue to have a place to discuss access control for CiviCRM Entity entity types. 

This can be a complex subject, because of all the contexts entities can be used in. 

Data can be displayed via:
Views
Drupal pages, e.g. civicrm-contact/1
Via display of entity reference fields on other entity types

Data can be edited via:
Drupal edit forms, e.g civicrm-contact/1/edit
Via entity reference field forms, with Entity Browser / Inline Entity form

Currently there is no user interface to set what roles can view/update/delete entities of CiviCRM entity types. 
Required permissions that a user's role(s) must have are hardcoded here:
https://github.com/eileenmcnaughton/civicrm_entity/blob/8.x-3.x/src/SupportedEntities.php

If there is no specific permission(s) defined, CE defaults to 'administer CiviCRM'

What permissions are required can be adjusted by implementing hook_civicrm_alter_drupal_entities(&$entity_types)

Additional, standard Drupal access control methodology can be used, such as hook_entity_access()
For instance, a developer can implement the above hook, and design different access requirements for viewing/editing contacts of different contact types / sub types.

Problems:
As it is, developers can design any access control scheme programmatically, but it is currently difficult for new site builders / non-developers to understand what permissions are required for users to see/edit/delete data in the various Drupal contexts, and change them.
ACLs and other CiviCRM access control mechanisms are not integrated out of the box. Should they be? Should they be for Views, but not other areas? 

Ideas:
We could add permissions to the standard Drupal permissions page, so that site builders can set permissions for roles in a "normal" Drupal way
We could provide a separate settings page that lists entity types, operations on those types, and roles which can access
Neither of the above ideas integrate CiviCRM ACLs in a meaningful or transparent way. 
We change nothing, but provide and improve documentation detailing "out of the box" behavior, and ways which they can be modified by developers.

Questions:
Should Drupal Views access control be different than other for Drupal pages such as /civicrm-contact/1 ?
Should all integrated entity types have Views integration "out of the box"? Currently they do, regardless of whether or not an entity type is enabled on the CiviCRM Entity settings page.
Should CE respect CiviCRM ACLs? This maybe advantageous to some CiviCRM implementers, but foreign to Drupal developers. 
What should be provided out of the box, vs. providing documentation for site builders and developers to modify them?
What contexts and use cases are not currently considered in this issue?

**Comment by jackrabbithanna** [comment]
@jitendrapurohit
Is there anything you'd like to add to kick off this discussion? You had made a PR we are evaluating here:
https://github.com/eileenmcnaughton/civicrm_entity/pull/262

This would improve upon access control, to give permissions for users to view contacts, based upon a contact's CiviCRM Relationship to another contact. 

This is another CiviCRM native permission scheme, different than ACLs. 

I'd like to discuss access control from a broad perspective, and also list and integrate ideas such as you provided this PR.

**Comment by jitendrapurohit** [comment]
I think the main concern here would be to make sure the functionalities that worked fine in d7 should be sorted in D8 as well?

Eg. If Parent user has a permission to view Child user (via drupal permission, civi relationship, ACL, etc), there shouldn't be any extra config required to allow "A to see B" on any page (views or civi entity contact page). 

Currently this fails if Parent user only has 

- `view my contact` drupal permission 
-  civi relationship permission for `view and update child contact`. 
 
Fixed in the PR 262.

>ACLs and other CiviCRM access control mechanisms are not integrated out of the box. Should they be? Should they be for Views, but not other areas?

So i think I'm in support to fix things in the module that provides the former. Not sure about other areas, but +1 for views, i.e, no extra config, just some code fixes to work as per Drupal + civi permissions.

Keen to hear other thoughts, I may not be considering the implications on the non-view part.

**Comment by jackrabbithanna** [comment]
Looking at the new APIv4 checkAccess API as a way to go for access control here. 
Need to make sure if all entity types are covered .. and what to do if people integrate a custom entity type and it may not have this capability .. how to fall back on sane defaults. 

I think for sure we get into Civi based access control for Drupal pages / Drupal edit forms 
Need to think about entity reference fields .. I think definitely when adding/editing/deleting with Inline Entity Form widget (or entity browser) .. Do we do it or for selecting an existing entity .. probably. 
Thinking maybe Views integration is made to work bypassing the checks. Could be open for debate, but I think at least having the option is nice. 
Think about do we offer configuration options for different types of access. Use APIv4 by default .. provide the existing way only if enabled in some "Advanced Settings" ?

**Comment by KarinG** [comment]
Re: Views -> I'd be in favour to keep access permissions as they were in D7 i.e. leverage Drupal Access (via Roles). That already works as is.

Re: Drupal Page View/Edit/etc -> I'd be in favour of leveraging Drupal Access -> similar to how Node Access modules allow you to let users with certain Roles View content/Add content etc - so also via Roles.

**Comment by jackrabbithanna** [comment]
I agree that wrt Views .. keep it where no special access control other than what can be set for the View. 
If there are problems Viewing rows in Views .. we handle that. 

For the Drupal pages, edit forms, deleting .. I'm on the fence. 

Using CiviCRM APIv4's upcoming way of checking access makes a lot of sense, and provides a "one way" to check if user should have access through its own contact record. This won't come into play until a future Civi version, so if we go with this, we have to check what Civi version and provide sane default / alternative. Is permissions via APIv4 better, which includes all of Civi's relationship or ACL type permission determination .. How important is it to determine access to say contacts using the same logic that Civi uses or will use? 

There is a good counter argument that permissions for these things should be done in a more pure "Drupal way" .. with something similar to what Karin proposed there, and I had proposed earlier. This would be very familiar to Drupal devs/implementers. 

It could be possible to either document or provide configuration option to use the APIv4 way. 
It could be possible to combine the two. We could have a Drupal user role based way of determining access, and then include a check with the APIv4 as well. 

It is also possible to provide a APIv4 way of determining access in an additional module bundled with the project.

Whatever we do, communicating how access control works in documentation or in the UI/UX of settings page is a necessity.

We don't have to decide now, the new feature in referenced PR is still a WIP.
