### ISSUE TITLE
Support Multi-valued Contact Reference custom fields

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/civicrm_entity#303]
Problem/Motivation
----------------------------------------
CiviCRM recently added support for multi-valued contact reference custom fields (5.34)
https://github.com/civicrm/civicrm-core/pull/18941/files

Neither in Views integration, Drupal pages, or Drupal edit forms handle this gracefully. 

Proposed resolution
----------------------------------------
Add necessary field formatters, views plugins, field widgets etc.. to fully support this new feature

**Comment by puresyntax71** [comment]
Noting there is a WIP PR at #307.
