### ISSUE TITLE
Proximity Filter only shows US States

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#310]
Problem/Motivation
----------------------------------------
![image](https://user-images.githubusercontent.com/5340555/121970748-75022380-cd34-11eb-8f3e-b370e78ab5e1.png)

Steps to reproduce
----------------------------------------
Build a Leaflet view per instructions and double check Canada is set as default Country - go back to the View -> still no Provinces available in the Select element. 

![image](https://user-images.githubusercontent.com/5340555/121970919-d5916080-cd34-11eb-8cc9-3fc9af303b31.png)

**Comment by jackrabbithanna** [comment]
MR resolved issue. Closing.
