### ISSUE TITLE
Filtering on a boolean custom field gives a php error and zero results in views

### ISSUE THREAD

**Issue by vingle** [eileenmcnaughton/civicrm_entity#314]
Problem/Motivation
----------------------------------------
Contacts have been given a yes/no custom field – and adding this as a filter in a view creates an error and displays zero results. If the view is saved, then it displays a whitescreen 'website encoutered an error' in the front end. NB - the custom field value will display in the view fine.

Steps to reproduce
----------------------------------------
Add a yes/no custom field associated with a contact, e.g. 'has health & safety training' – and populate with some data. Create a view of Civi contacts and try to filter on it.

Full error messages
----------------------------------------
In view

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal9.civicrm_value_staff_83' doesn't exist: SELECT "civicrm_contact"."id" AS "id" FROM {civicrm_contact} "civicrm_contact" LEFT JOIN {civicrm_value_staff_83} "civicrm_value_staff_83" ON civicrm_contact.id = civicrm_value_staff_83.entity_id WHERE ((civicrm_contact.contact_sub_type = :civicrm_contact_contact_sub_type)) AND ("civicrm_value_staff_83"."are_they_a_staff_member__698" = :db_condition_placeholder_0) LIMIT 30 OFFSET 0; Array ( [:civicrm_contact_contact_sub_type] => Board [:db_condition_placeholder_0] => 1 )`

In Drupal log

`Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Staff and Board[staff_and_board]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal9.civicrm_value_staff_83' doesn't exist: SELECT "civicrm_contact"."id" AS "id" FROM {civicrm_contact} "civicrm_contact" LEFT JOIN {civicrm_value_staff_83} "civicrm_value_staff_83" ON civicrm_contact.id = civicrm_value_staff_83.entity_id WHERE ((civicrm_contact.contact_sub_type = :civicrm_contact_contact_sub_type)) AND ("civicrm_value_staff_83"."are_they_a_staff_member__698" = :db_condition_placeholder_0) LIMIT 30 OFFSET 0; Array ( [:civicrm_contact_contact_sub_type] => Board [:db_condition_placeholder_0] => 1 ) in Drupal\views\Plugin\views\query\Sql->execute() (line 1548 of /home/drupal/public_html/web/core/modules/views/src/Plugin/views/query/Sql.php).`

**Comment by jackrabbithanna** [comment]
Do you have your Civi tables in a separate database from Drupal? 

Its possible you need to add your custom field table to the $databases prefix information in your settings.php or settings.local.php

You can find what to set at: civicrm/admin/setting/uf?reset=1
"Views integration settings"

**Comment by vingle** [comment]
Thanks Mark - it's not that unfortauntely, but I agree it looks like it! All the tables are in the same dbse. I just dble checked and they all have the same innodb/utf8_unicode_ci type and collation too.

**Comment by puresyntax71** [comment]
Hi @vingle,

Yeah, happen to still have this issue? Can you check if you have backticks (`) in your database names in settings*.php? There isn't suppose to be backticks unlike in D8.

Correct example is:

```php
  'civicrm_uf_group'                                           => 'civicrm.',
  'civicrm_uf_join'                                            => 'civicrm.',
  'civicrm_uf_match'                                           => 'civicrm.',
```

**Comment by vingle** [comment]
Hi @puresyntax71 - sorry for the slow reply. Have just checked and there's no backticks I can find.

**Comment by puresyntax71** [comment]
Yeah, sorry, not entirely sure what the problem might be. I tried it on a fresh install of Drupal 9.2, CiviCRM 5.43.2, and CE (dev version).

Drupal and CiviCRM are on the same table as well. I was getting this on views:

```sql
SELECT "civicrm_contact"."id" AS "id"
FROM
{civicrm_contact} "civicrm_contact"
LEFT JOIN {civicrm_value_test_1} "civicrm_value_test_1" ON civicrm_contact.id = civicrm_value_test_1.entity_id
WHERE ("civicrm_value_test_1"."test_1" = '1') AND ("civicrm_value_test_1"."has_health_safety_training_2" = '1')
LIMIT 11 OFFSET 0
```

These are "Yes/No" fields. Yeah, guessing the table "civicrm_value_staff_83" actually exists? Perhaps try other custom groups or creating a new field under the same custom group for testing.

**Comment by jackrabbithanna** [comment]
Closing out old issues, we were unable to replicate the issue. If issue persists with recent version please create issue at https://www.drupal.org/project/issues/civicrm_entity?categories=All
