### ISSUE TITLE
Layout Builder context exception for Events and Activities

### ISSUE THREAD

**Issue by jackrabbithanna** [eileenmcnaughton/civicrm_entity#317]
Problem/Motivation
----------------------------------------
If you enable Event entity type to use Layout Builder, and then clear caches, the Manage Layout page throws exception:

Drupal\Component\Plugin\Exception\MissingValueContextException: Required contexts without a value: entity in Drupal\Core\Plugin\Context\ContextHandler->applyContextMapping() (line 161 of core/lib/Drupal/Core/Plugin/Context/ContextHandler.php). 

I suspect this is due to the change where there are multiple bundles now based on event_type .. because other entity types work with Layout Builder without issue with latest code from here. 

@KarinG @mglaman 

Matt, is this something you can take a look at? 

I see you had encountered something similar here with product variations:
https://www.drupal.org/project/commerce/issues/2952529

**Comment by genaskvare** [comment]
@puresyntax71 - Can you take this on? It will be valuable to get this issue knocked out.

**Comment by puresyntax71** [comment]
Noting that I've tested this but unable to reproduce.

Testing process:

# Disable CiviCRM event in /admin/structure/civicrm-entity/settings.
# Confirm that you get 404 page when going to /admin/structure/civicrm-entity/civicrm-event.
# Enable CiviCRM event in /admin/structure/civicrm-entity/settings..
# Enable "Use layout builder" in "Manage display" at /admin/structure/civicrm-entity/civicrm-event/display.
# Click on "Manage layout".
# Either "Save" or "Discard" the changes.

I've enabled layout builder on Events and enabled the "Allow each civicrm event to have its layout customized." option as well. I tested this in both Event and Options Value (non bundle CE).

So far I haven't encountered issues.

Perhaps it works fine for fresh installs and latest version of CiviCRM entity.
