### ISSUE TITLE
Custom date fields that are empty show current time in views

### ISSUE THREAD

**Issue by hansrossel** [eileenmcnaughton/civicrm_entity#318]
Problem/Motivation
----------------------------------------
When using custom date fields the ones that are empty (NULL) show as the current date in views

Steps to reproduce
----------------------------------------
- Create a custom date field
- Show the field in a Drupal views table
- Contacts that have this field empty will have the current date in the column

Proposed resolution
----------------------------------------
Leave the field empty in the view when its value is NULL

**Comment by hansrossel** [comment]
When I check with hook_views_pre_render the field is empty. 
Also hook_preprocess_views_view_field shows the field empty.
So it must happen somewhere at output, not sure where.

I fixed it with a workaround: 
```
function MYMODULE_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  if ($view->id() == 'MYVIEW') {
    if ($variables['field']->field == 'year_founded_142') {
      $year = $variables['field']->getValue($variables['row']);
      if (empty($year)) {
        $variables['output'] = '';
      }
    }
  }
}
```

**Comment by jackrabbithanna** [comment]
MR ready for testing, for the fix for this.
