### ISSUE TITLE
Add user format to CiviCRM Entity

### ISSUE THREAD

**Issue by edvanleeuwen** [eileenmcnaughton/civicrm_entity#334]
Problem/Motivation
----------------------------------------
Feature request: I would like to have the following user format added to CiviCRM Entity.

Steps to reproduce
----------------------------------------
_Steps in order to reproduce the bug._

Proposed resolution
----------------------------------------
In civicrm_entity.module, function _civicrm_entity_options_username_format:

```
 `'nick.middle.last' => t('Nick.Middle.Last'), 'nick.middlelast' => t('Nick.MiddleLast'),`
```

In civicrm_entity.module, function civicrm_entity_action_create_user:

```
case 'nick.middle.last':
   if (!empty($contact['middle_name'])) {
     $params['name'] = _civicrm_entity_clean_login_name(trim($contact['nick_name']) . "." . trim($contact['middle_name']) . "." . trim($contact['last_name']));
   } else {
     $params['name'] = _civicrm_entity_clean_login_name(trim($contact['nick_name']) . "." . trim($contact['last_name']));
   }
   break;
case 'nick.middlelast':
   if (!empty($contact['middle_name'])) {
     $params['name'] = _civicrm_entity_clean_login_name(trim($contact['nick_name']) . "." . trim($contact['middle_name']) . trim($contact['last_name']));
   } else {
     $params['name'] = _civicrm_entity_clean_login_name(trim($contact['nick_name']) . "." . trim($contact['last_name']));
   }
   break;
```

**Comment by edvanleeuwen** [comment]
I have attempted to do something with this. I ended up with a changed file, which is called https://github.com/eileenmcnaughton/civicrm_entity/compare/7.x-2.x...edvanleeuwen:patch-2

What should I do next?

**Comment by jackrabbithanna** [comment]
Merged, closing issue
