### ISSUE TITLE
View Mode no longer renders

### ISSUE THREAD

**Issue by jdelon02** [eileenmcnaughton/civicrm_entity#335]
Problem/Motivation
----------------------------------------
I have an existing site that uses civcirm entity to render civi data using drupal.  We output that data using several different view modes.  The view modes use Display Suite, Bootstrap Layouts, and Field Group modules to control layout, grouping, etc...   

When I upgrade to Beta3 version, the view mode layouts all stop working and revert back to only rendering default view mode.  If I inspect, I can see that none of the layout generated code is being rendered at all.  For example, if the default view mode is set to use a 50/50 left right layout, the divs that should be generated to control that are no longer there.

The reason that I think this is an issue with this module is that non-civi entities render correctly.  

Steps to reproduce
----------------------------------------
Have an existing site using civicrm_entity with a release prior to beta3
Have the following modules used to control layout:
DS
Field Group
Bootstrap Layouts (optional)
Choose a layout for a civicrm entity and add a field group or two for organizing the output.
See that the civicrm entity is rendering correctly.
Assuming it is, upgrade to beta3.  
Now, the rendering will be broken.

I should add that this is happening with rendering civi events.  This particular site only needs to display events, but I would assume other civi entities would have the same issue.

I would also add that we render civi events using view modes through views, and once the upgrade to beta3 happened, the rendering was broken there as well.

Copied from: https://www.drupal.org/project/civicrm_entity/issues/3247663

Proposed resolution
----------------------------------------
_Suggestions to fix the bug or a resolution for the problem._

**Comment by mglaman** [comment]
> Display Suite, Bootstrap Layouts, and Field Group

Okay so there are two points of possible failure:

* Display Suite
* Field Group

This _shouldn't_ have broken. The hard part is reproducing. Are you able to upload a screenshot of the view display mode configuration to show some examples? Also, a really simplistic answer of "try re-saving the entity view display" to see if that fixes as a "turn it off and on again".

**Comment by jackrabbithanna** [comment]
PR for this in now:
https://github.com/eileenmcnaughton/civicrm_entity/pull/381

At least it will respect which view display mode is used for rendering in Views and Entity Reference fields

Put in new release version 3.3 .. 
Now if other issues with Display Suite and Field groups etc.. we will tackle that separately. 
Closing for now.
