### ISSUE TITLE
Views Multiple Field Settings has no effect

### ISSUE THREAD

**Issue by jaomalley** [eileenmcnaughton/civicrm_entity#342]
Problem/Motivation
----------------------------------------
8.x-3.0-beta3 was the last version on Drupal 8 where Views Multiple Field Settings worked properly. I upgraded to Drupal 9 and discovered this was no longer the case. I just upgraded to version civicrm entity version 3 released on 2 december and the problem persists. Multiple value custom fields will not respect the settings of "Multiple Field Settings" within views.

Steps to reproduce
----------------------------------------
Drupal 9 and 8.8
civicrm_entity 3.0 and 8.x-3.0-beta3
Civicrm 5.4x (same across multiple versions)
MariaDB 10.3

I rolled back my installation to 8.8 and tested it against civicrm_entity 8.x-3.0-beta3 and Views multiple field settings does indeed work as expected. Upgraded to 9 again without changing civicrm_entity multiple field settings breaks. Upgrade to civicrm_entity 3.0 and it stays broken.

Proposed resolution
----------------------------------------
I note that EntityManager has been deprecated in Drupal 9.x, but was available up to Drupal 8.8 and has been replaced with EntityTypeManage in current versions. Seems to be the only large change between the two instances. Could there still be some mismatch between views and civicrm_entity still?

**Comment by jackrabbithanna** [comment]
We are aware of some issues with Civi custom field groups set to multiple values, and will continue to work on them as time/budget allows. There are several issues in the D.O issue queue, and moving forward we are switching to using that. This issue is old, and some issues have definitely been fixed.
