### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by mglaman** [eileenmcnaughton/civicrm_entity#348]
Problem/Motivation
----------------------------------------
The tests are _painfully_ slow due to Drupal installing and dropping tables over and over and over again.

Steps to reproduce
----------------------------------------
Check out those GitHub Actions

Proposed resolution
----------------------------------------
Borrow ideas from ThunderCMS, which leverages an initial database dump.

https://github.com/thunder/thunder-distribution/blob/4ddf56119c3005e1eb469d1e1f6241d9c416284d/tests/src/Traits/ThunderTestTrait.php#L113-L126

https://github.com/thunder/thunder-distribution/blob/4ddf56119c3005e1eb469d1e1f6241d9c416284d/.github/workflows/tests.yml#L242

**Comment by jackrabbithanna** [comment]
MRs were merged, closing issue

**Comment by jackrabbithanna** [comment]
I think: https://github.com/eileenmcnaughton/civicrm_entity/pull/351
https://github.com/eileenmcnaughton/civicrm_entity/pull/350

**Comment by demeritcowboy** [comment]
Ok thanks yes those might have added some improvements. This was about each test needing to install both drupal and civi from scratch each time. If it could just do it once and then reload a saved db, or some other strategy, it would save significant time for each test.
