### ISSUE TITLE
Views relationships missing: Line Items to Price Fields, Contributions to Contribution Status, Price Field to Price Value, ...

### ISSUE THREAD

**Issue by herbdool** [eileenmcnaughton/civicrm_entity#352]
Problem/Motivation
----------------------------------------
I'm using 8.x-3.0 and trying to recreate a View we had on a D7 site that included line items, contributions, price fields, values, etc (it was built just using the recommended db prefix for D7). A lot of the relationships seem to be missing using civicrm_entity. I've tried starting with different base tables: line items, contributions, price fields and doesn't seem to make a difference. I haven't found: relationship to Contribution Status, Line Items to Price Fields/Values.

Steps to reproduce
----------------------------------------
Create a View with base table of Line Items (or Contributions, etc). Then try to add a relationship to the Price Field or Price Value.

Proposed resolution
----------------------------------------
Have these available.

**Comment by jackrabbithanna** [comment]
We had added line item, price field, price field values entity type integration, and Views support for these. It has been possible to start with a base table of civicrm_contribution and join to line items, then price fields, then price field values. Issue was just not updated. Closing
