### ISSUE TITLE
Adding a relationship of User to Contact produces sql access violation

### ISSUE THREAD

**Issue by herbdool** [eileenmcnaughton/civicrm_entity#353]
Problem/Motivation
----------------------------------------
I've created a View of Contacts using 8.x-3.0. So far so good. Records show up. But when I add a relationship to User, I get:

> SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'xxxx'@'xxx.xx.x.x' for table 'users_field_data': SELECT "civicrm_contact"."id" AS "id", "users_field_data_civicrm_uf_match"."uid" AS "users_field_data_civicrm_uf_match_uid" FROM "civicrm_contact" "civicrm_contact" LEFT JOIN "civicrm_uf_match" "civicrm_uf_match" ON civicrm_contact.id = civicrm_uf_match.contact_id LEFT JOIN drupal9.users_field_data "users_field_data_civicrm_uf_match" ON civicrm_uf_match.uf_id = users_field_data_civicrm_uf_match.uid LIMIT 51 OFFSET 0; Array ( )

Database settings seem fine. (Prefix hack is *not* enabled).

**Comment by jackrabbithanna** [comment]
I feel like this is not an issue with CE, or was resolved. Closing for now. If persists, please make an issue in the Drupal.org project issue queue. Closing.
