### ISSUE TITLE
Views Filter Handling of Custom FIelds with Multiple Choice Options

### ISSUE THREAD

**Issue by herbdool** [eileenmcnaughton/civicrm_entity#354]
Problem/Motivation
----------------------------------------
I've got an custom field with multiple choice options that I've added as an exposed filter. I've tried with allowing a single selection and multiple. I get no results except when left as "Any".

The SQL query snippet looks like: `CAST(civicrm_value_accreditation_information_5.area_of_expertise_179 AS BINARY) RLIKE BINARY '1'`. If I manually run the query I also get nothing but changing it to what the option actually is storing is "Academic" so `CAST(civicrm_value_accreditation_information_5.area_of_expertise_179 AS BINARY) RLIKE BINARY 'Academic'` does work. Not sure where the 1 is coming from.

It's possible it's coming from a previous filter (not exposed) which is a checkbox so it's either 1 or 0.

Steps to reproduce
----------------------------------------
Need a couple custom fields with multiple choice options (and perhaps a checkbox). Add some data and then add these fields to a View as exposed filters.

I haven't tested on a fresh site so not sure.

**Comment by chaplincircle** [comment]
Only works when the civi option value = 1 or 2 ?

**Comment by jackrabbithanna** [comment]
There had been updates for this, and should now work. I know I've used custom fields with select / checkboxes in client work. If there is specific issue still existing please create issue in the Drupal.org issue queue. https://www.drupal.org/project/issues/civicrm_entity?categories=All
